function project_root = setup_project_paths()
%SETUP_PROJECT_PATHS Add active source folders to the MATLAB path.

    persistent cached_root

    if isempty(cached_root) || ~isfolder(cached_root)
        cached_root = fileparts(mfilename('fullpath'));
    end

    project_root = cached_root;
    active_dirs = { ...
        'configs', ...
        'main', ...
        'channels', ...
        'mimo', ...
        'ofdm', ...
        'coding', ...
        'modulation', ...
        'utils', ...
        'plotting', ...
        'validation'};

    for idir = 1:numel(active_dirs)
        addpath(fullfile(project_root, active_dirs{idir}));
    end
end
