function validation = run_validation_suite(baseCfg)
%RUN_VALIDATION_SUITE Execute lightweight validation checks for the framework.

    validation = struct();
    validation.no_noise_2x1 = run_noiseless_roundtrip(override_config(baseCfg, ...
        'N_Tx', 2, 'N_Rx', 1, 'channel_model', 'AWGN', 'Coded_method', 'NULL', ...
        'N_mod', 2, 'N_frame', 1, 'scenario_name', 'validation_no_noise_2x1'));

    validation.no_noise_1x1 = run_noiseless_roundtrip(override_config(baseCfg, ...
        'N_Tx', 1, 'N_Rx', 1, 'channel_model', 'AWGN', 'Coded_method', 'NULL', ...
        'N_mod', 2, 'N_frame', 1, 'scenario_name', 'validation_no_noise_1x1'));

    validation.no_noise_2x2 = run_noiseless_roundtrip(override_config(baseCfg, ...
        'N_Tx', 2, 'N_Rx', 2, 'channel_model', 'AWGN', 'Coded_method', 'NULL', ...
        'N_mod', 2, 'N_frame', 1, 'scenario_name', 'validation_no_noise_2x2'));

    validation.no_noise_2x4 = run_noiseless_roundtrip(override_config(baseCfg, ...
        'N_Tx', 2, 'N_Rx', 4, 'channel_model', 'AWGN', 'Coded_method', 'NULL', ...
        'N_mod', 2, 'N_frame', 1, 'scenario_name', 'validation_no_noise_2x4'));

    validation.no_noise_4x4 = run_noiseless_roundtrip(override_config(baseCfg, ...
        'N_Tx', 4, 'N_Rx', 4, 'channel_model', 'AWGN', 'Coded_method', 'NULL', ...
        'N_mod', 2, 'N_frame', 1, 'scenario_name', 'validation_no_noise_4x4'));

    validation.no_noise_estimated_csi = run_noiseless_roundtrip(override_config(baseCfg, ...
        'N_Tx', 2, 'N_Rx', 2, 'channel_model', 'AWGN', 'Coded_method', 'NULL', ...
        'N_mod', 2, 'N_frame', 1, 'enable_pilot_estimation', true, ...
        'compare_csi_with_ideal', false, 'scenario_name', 'validation_no_noise_estimated_csi'));

    validation.rs_full_frame = run_noiseless_roundtrip(override_config(baseCfg, ...
        'N_Tx', 2, 'N_Rx', 2, 'channel_model', 'AWGN', 'Coded_method', 'RS', ...
        'N_mod', 2, 'N_frame', 1, 'scenario_name', 'validation_rs_full_frame'));

    validation.ldpc_full_frame = run_noiseless_roundtrip(override_config(baseCfg, ...
        'N_Tx', 2, 'N_Rx', 2, 'channel_model', 'AWGN', 'Coded_method', 'LDPC', ...
        'N_mod', 2, 'N_frame', 1, 'scenario_name', 'validation_ldpc_full_frame'));

    validation.rs_codec_sanity = run_rs_codec_sanity();
    validation.ldpc_codec_sanity = run_ldpc_codec_sanity(baseCfg);
    validation.awgn_theory = validate_awgn_theory(baseCfg.output_dir, baseCfg.show_figures);
    validation.urlcc_metrics_guard = local_validate_urlcc_metrics(baseCfg);
    validation.finite_blocklength_guard = local_validate_finite_blocklength(baseCfg);
    validation.dynamic_channel_smoke = local_validate_dynamic_channel(baseCfg);
    validation.dynamic_tdl_profiles_smoke = local_validate_dynamic_tdl_profiles(baseCfg);
    validation.mmse_estimator_smoke = local_validate_estimator(baseCfg, 'MMSE', 'DYNAMIC-RAYLEIGH');
    validation.kalman_estimator_smoke = local_validate_estimator(baseCfg, 'KALMAN', 'DYNAMIC-RICIAN');
    validation.bayesian_estimator_smoke = local_validate_estimator(baseCfg, 'BAYESIAN', 'DYNAMIC-RICIAN');
    validation.score_guard = local_validate_score_guard(baseCfg);
end

function guard = local_validate_score_guard(cfg)
    BER = 2e-2 * ones(size(cfg.EbN0s_dB));
    metrics = evaluate_curve_metrics(cfg.EbN0s_dB, BER, cfg.eta_eff);

    guard = struct();
    guard.metrics = metrics;
    guard.passed = metrics.score < 100 && all(~isfinite(metrics.reqSNR));
end

function guard = local_validate_urlcc_metrics(cfg)
    testCfg = override_config(cfg, ...
        'N_symbol', 4, 'N_frame', 1, 'EbN0s_dB', [0 4], ...
        'scenario_name', 'validation_urlcc_metrics');
    result = run_single_case(testCfg);
    primary = result.mode_results.(result.primary_csi_mode);

    guard = struct();
    guard.payload_bits_per_frame = primary.urlcc.payload_bits_per_frame;
    guard.frame_duration_s = primary.urlcc.frame_duration_s;
    guard.latency_proxy_s = primary.urlcc.latency_proxy_s;
    guard.passed = all(primary.BLER >= 0 & primary.BLER <= 1) && ...
        all(primary.urlcc.effective_throughput_bps >= 0) && ...
        all(primary.urlcc.nominal_throughput_bps > 0) && ...
        all(primary.urlcc.latency_proxy_s > 0) && ...
        all(primary.urlcc.reliability_target_confidence(:) >= 0 & ...
            primary.urlcc.reliability_target_confidence(:) <= 1) && ...
        all(primary.urlcc.bler_confidence_interval(:) >= 0 & ...
            primary.urlcc.bler_confidence_interval(:) <= 1);
end

function guard = local_validate_finite_blocklength(cfg)
    packetModes = {'short', 'medium', 'long'};
    cases = repmat(struct( ...
        'mode', '', ...
        'packet_bits', NaN, ...
        'packet_symbols', NaN, ...
        'passed', false), 1, numel(packetModes));

    for imode = 1:numel(packetModes)
        caseCfg = override_config(cfg, ...
            'packet_length_mode', packetModes{imode}, ...
            'N_frame', 1, 'EbN0s_dB', [0 4], ...
            'channel_model', 'AWGN', 'Coded_method', 'Conv', 'N_mod', 2, ...
            'scenario_name', ['validation_packet_' packetModes{imode}]);
        result = run_single_case(caseCfg);
        primary = result.mode_results.(result.primary_csi_mode);

        cases(imode).mode = packetModes{imode};
        cases(imode).packet_bits = result.packet_length_bits;
        cases(imode).packet_symbols = result.packet_length_symbols;
        cases(imode).passed = result.packet_length_symbols == caseCfg.N_symbol && ...
            result.packet_length_bits > 0 && ...
            size(primary.urlcc.reliability_target_met, 1) == numel(caseCfg.bler_target_thresholds) && ...
            size(primary.urlcc.reliability_target_confidence, 1) == numel(caseCfg.bler_target_thresholds) && ...
            all(primary.urlcc.effective_throughput_bps >= 0) && ...
            all(primary.urlcc.latency_proxy_s > 0);
    end

    guard = struct();
    guard.cases = cases;
    guard.passed = all([cases.passed]) && ...
        cases(1).packet_symbols < cases(2).packet_symbols && ...
        cases(2).packet_symbols < cases(3).packet_symbols;
end

function guard = local_validate_dynamic_channel(cfg)
    caseCfg = override_config(cfg, ...
        'channel_model', 'DYNAMIC-RAYLEIGH', ...
        'enable_dynamic_channel', true, ...
        'use_fractional_delay', true, ...
        'velocity_mps', 25, ...
        'enable_pilot_estimation', true, ...
        'channel_estimation_method', 'MMSE', ...
        'equalizer_type', 'MMSE', ...
        'N_frame', 1, 'EbN0s_dB', [0 4], ...
        'scenario_name', 'validation_dynamic_channel');
    result = run_single_case(caseCfg);
    primary = result.mode_results.(result.primary_csi_mode);

    guard = struct();
    guard.scenario = result.scenario_tag;
    guard.ber = result.BER;
    guard.nmse = primary.channel_nmse;
    guard.passed = all(isfinite(result.BER)) && ...
        all(isfinite(primary.channel_nmse) | isnan(primary.channel_nmse)) && ...
        any(isfinite(primary.channel_nmse));
end

function guard = local_validate_estimator(cfg, methodName, channelModel)
    caseCfg = override_config(cfg, ...
        'channel_model', channelModel, ...
        'enable_dynamic_channel', true, ...
        'use_fractional_delay', true, ...
        'velocity_mps', 20, ...
        'enable_pilot_estimation', true, ...
        'channel_estimation_method', methodName, ...
        'equalizer_type', 'MMSE', ...
        'N_frame', 1, 'EbN0s_dB', [0 4], ...
        'scenario_name', ['validation_' lower(methodName)]);
    result = run_single_case(caseCfg);
    primary = result.mode_results.(result.primary_csi_mode);

    guard = struct();
    guard.method = methodName;
    guard.channel = channelModel;
    guard.ber = result.BER;
    guard.nmse = primary.channel_nmse;
    guard.passed = all(isfinite(result.BER)) && any(isfinite(primary.channel_nmse));
end

function guard = local_validate_dynamic_tdl_profiles(cfg)
    profileList = {'TDL-A', 'TDL-B', 'TDL-C', 'TDL-D'};
    cases = repmat(struct( ...
        'profile', '', ...
        'ber', [], ...
        'nmse', [], ...
        'passed', false), 1, numel(profileList));

    for iprofile = 1:numel(profileList)
        caseCfg = override_config(cfg, ...
            'channel_model', profileList{iprofile}, ...
            'enable_dynamic_channel', true, ...
            'use_fractional_delay', true, ...
            'velocity_mps', 20, ...
            'enable_pilot_estimation', true, ...
            'channel_estimation_method', 'MMSE', ...
            'equalizer_type', 'MMSE', ...
            'packet_length_mode', 'short', ...
            'N_frame', 1, 'EbN0s_dB', 0, ...
            'scenario_name', ['validation_' lower(profileList{iprofile}) '_dyn']);
        result = run_single_case(caseCfg);
        primary = result.mode_results.(result.primary_csi_mode);

        cases(iprofile).profile = profileList{iprofile};
        cases(iprofile).ber = result.BER;
        cases(iprofile).nmse = primary.channel_nmse;
        cases(iprofile).passed = all(isfinite(result.BER)) && any(isfinite(primary.channel_nmse));
    end

    guard = struct();
    guard.cases = cases;
    guard.passed = all([cases.passed]);
end
